### ISSUE TITLE
README file update

### ISSUE THREAD

**Issue by andriyun** [os2datascanner/os2datascanner#10]
There was change in `docker-compose.yml` file
https://github.com/os2datascanner/os2datascanner/commit/1b4bb608f10e43228c8ed90785e51a6ee19f432c#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

But this change is not reflected in README file.

for example command 
```
docker-compose exec admin-application python manage.py createsuperuser
```
doesn't work

**Comment by dals83** [comment]
That has been corrected in https://github.com/os2datascanner/os2datascanner/commit/3f95d094d0d05050daf695ed2caefe506ef50b05
