### ISSUE TITLE
OS2Datascanner collaboration request

### ISSUE THREAD

**Issue by andriyun** [os2datascanner/os2datascanner#13]
Hi there

I'm a developer from Bellcom and we are interested in contributing into the OS2Datascanner project. Bellcom has customers that are using OS2Datascanner. From time to time we are getting support requests from them for fixing issues or developing new features.

I've experienced that version 3 has gotten new features and user interface changes
for example in `admin_application` between releases `3.7.1` and `3.9.0`
So it looks like version 3 is under active development now, isn't it?

On the ground of this I'd like to know if there is a ROADMAP for the OS2Datascanner project? It would be very useful for us (and other contributors who might be interested in using this project) to understand what is going to be added to the project in the future and when.

Based on general rules for open source contribution can we start to add changes we have right away. How would these changes get merged into the original repository. ?

Are there specific rules you have for accepting changes from OS2Datascanner collaborators?

We are collaborating on other projects with Magenta. For instance the [OS2forms](https://github.com/OS2Forms/os2forms8) project. If you need to verify that we follow “the process” / coding standards.

**Comment by andriyun** [comment]
Just kind reminder that we are still looking forward for any comment here :)
I'll tag top 3 contributor here, just in case:
- @magenta-af 
- @magenta1455 
- @agger-magenta

**Comment by dals83** [comment]
Hi Andriyun,

Glad to hear that others are using OS2datascanner. 

If you will like to contribute to OS2datascanner, all you have to do is send a pull request, then we at Magenta will have a look at it.
If/when the changes are accepted they will be merged to this repository. We at Magenta will then make sure they are part of the next release tag together with all our changes.
It can be that we find the changes are good but needs to be part of a larger context. In that case we at Magenta will take the changes and add it directly to our development repo. 
If we decide to add the changes this way we will make sure that the commit message or a comment in the code will mention who we got the changes from.
We do not have a formal document describing all the standards and best practices we follow. So here are the most important:
* We use flake8 with a line length at 87.
* We add unit tests to all new features and code changes.
* In all new files Mozilla license are added to the top of the file (except migrations).
* All new methods and complicated logic is described.

Can you tell me a little bit about how you use OS2datascanner and what data sources you are scanning?
That way I can narrow the scope of the roadmap sharing.
