### ISSUE TITLE
REST API support

### ISSUE THREAD

**Issue by DeepDiver1975** [os2datascanner/os2datascanner#6]
Are there any plans to provide a REST API - specifically for automated scanning of documents.

This might be of interest for various integrations with systems which store and manage the life cycle of these files.

THX

**Comment by dals83** [comment]
Hi @DeepDiver1975,

A REST API is on its way. We expect it will be available within the first half year of 2021.
If you have any special needs or want more detailed information about what is coming you are very welcome to write to info@magenta.dk

Br,
Danni

**Comment by dals83** [comment]
Hi @DeepDiver1975,

There is a REST API now. You can read more about it here: https://github.com/os2datascanner/os2datascanner/blob/master/doc/pages/api.rst
